
package com.calvinklein.rewards.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ckrewards", targetNamespace = "http://service.rewards.calvinklein.com/", wsdlLocation = "http://localhost:7001/CKPreferredProgram_VS/ckrewards?wsdl")
public class Ckrewards
    extends Service
{

    private final static URL CKREWARDS_WSDL_LOCATION;
    private final static WebServiceException CKREWARDS_EXCEPTION;
    private final static QName CKREWARDS_QNAME = new QName("http://service.rewards.calvinklein.com/", "ckrewards");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/CKPreferredProgram_VS/ckrewards?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CKREWARDS_WSDL_LOCATION = url;
        CKREWARDS_EXCEPTION = e;
    }

    public Ckrewards() {
        super(__getWsdlLocation(), CKREWARDS_QNAME);
    }

    public Ckrewards(WebServiceFeature... features) {
        super(__getWsdlLocation(), CKREWARDS_QNAME, features);
    }

    public Ckrewards(URL wsdlLocation) {
        super(wsdlLocation, CKREWARDS_QNAME);
    }

    public Ckrewards(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CKREWARDS_QNAME, features);
    }

    public Ckrewards(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ckrewards(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "LoginPort")
    public Login getLoginPort() {
        return super.getPort(new QName("http://service.rewards.calvinklein.com/", "LoginPort"), Login.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "LoginPort")
    public Login getLoginPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.rewards.calvinklein.com/", "LoginPort"), Login.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CKREWARDS_EXCEPTION!= null) {
            throw CKREWARDS_EXCEPTION;
        }
        return CKREWARDS_WSDL_LOCATION;
    }

}
