
package com.bootcamp.automobiles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutomobileImplService", targetNamespace = "http://automobiles.bootcamp.com/", wsdlLocation = "http://localhost:7001/SoapWebService/AutomobileImplService?wsdl")
public class AutomobileImplService
    extends Service
{

    private final static URL AUTOMOBILEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTOMOBILEIMPLSERVICE_EXCEPTION;
    private final static QName AUTOMOBILEIMPLSERVICE_QNAME = new QName("http://automobiles.bootcamp.com/", "AutomobileImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/SoapWebService/AutomobileImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTOMOBILEIMPLSERVICE_WSDL_LOCATION = url;
        AUTOMOBILEIMPLSERVICE_EXCEPTION = e;
    }

    public AutomobileImplService() {
        super(__getWsdlLocation(), AUTOMOBILEIMPLSERVICE_QNAME);
    }

    public AutomobileImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTOMOBILEIMPLSERVICE_QNAME, features);
    }

    public AutomobileImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTOMOBILEIMPLSERVICE_QNAME);
    }

    public AutomobileImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTOMOBILEIMPLSERVICE_QNAME, features);
    }

    public AutomobileImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomobileImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Motors
     */
    @WebEndpoint(name = "AutomobileImplPort")
    public Motors getAutomobileImplPort() {
        return super.getPort(new QName("http://automobiles.bootcamp.com/", "AutomobileImplPort"), Motors.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Motors
     */
    @WebEndpoint(name = "AutomobileImplPort")
    public Motors getAutomobileImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://automobiles.bootcamp.com/", "AutomobileImplPort"), Motors.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTOMOBILEIMPLSERVICE_EXCEPTION!= null) {
            throw AUTOMOBILEIMPLSERVICE_EXCEPTION;
        }
        return AUTOMOBILEIMPLSERVICE_WSDL_LOCATION;
    }

}
